#
#  Build Angular source (legacy) from originally installed node_modules
#   * avoids version discrepancies from older npm modules
#   * copy code, vendor support modules and build
#   * copy (cp) out build artifacts, in Makefile
#
FROM node:6.5

MAINTAINER Greg Milligan <xybersolve@gmail.com>

WORKDIR /usr/app
ADD . /usr/app

RUN npm run build:prod
